
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/CMSIS/Include
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/CMSIS/Device/ST/STM32F1xx/Include
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/STM32F1xx_HAL_Driver/Inc
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/STM32F1xx_HAL_Driver

CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/drivers/uart
CINCLUDE_FILE += catOS/include

CINCLUDE_FILE += user
CINCLUDE_FILE += user/bsp/board_led
CINCLUDE_FILE += user/bsp/key


subdir-y += bsp

obj-y += main.o

include $(RULE_DIR)/rules.mk
