
CINCLUDE_FILE += user

CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/CMSIS/Include
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/CMSIS/Device/ST/STM32F1xx/Include
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/Libraries/STM32F1xx_HAL_Driver/Inc


#HAL_LIB_DRIVER
obj-y += stm32f1xx_hal_adc.o
obj-y += stm32f1xx_hal_can.o
obj-y += stm32f1xx_hal_cec.o
obj-y += stm32f1xx_hal_cortex.o
obj-y += stm32f1xx_hal_crc.o
obj-y += stm32f1xx_hal_dac_ex.o
obj-y += stm32f1xx_hal_dac.o
obj-y += stm32f1xx_hal_dma.o
obj-y += stm32f1xx_hal_eth.o
obj-y += stm32f1xx_hal_flash_ex.o
obj-y += stm32f1xx_hal_flash.o
obj-y += stm32f1xx_hal_gpio_ex.o
obj-y += stm32f1xx_hal_gpio.o
obj-y += stm32f1xx_hal_hcd.o
obj-y += stm32f1xx_hal_i2c.o
obj-y += stm32f1xx_hal_i2s.o
obj-y += stm32f1xx_hal_irda.o
obj-y += stm32f1xx_hal_iwdg.o
obj-y += stm32f1xx_hal_mmc.o
obj-y += stm32f1xx_hal_nand.o
obj-y += stm32f1xx_hal_nor.o
obj-y += stm32f1xx_hal_pccard.o
obj-y += stm32f1xx_hal_pcd_ex.o
obj-y += stm32f1xx_hal_pcd.o
obj-y += stm32f1xx_hal_pwr.o
obj-y += stm32f1xx_hal_rcc_ex.o
obj-y += stm32f1xx_hal_rcc.o
obj-y += stm32f1xx_hal_rtc_ex.o
obj-y += stm32f1xx_hal_rtc.o
obj-y += stm32f1xx_hal_sd.o
obj-y += stm32f1xx_hal_smartcard.o
obj-y += stm32f1xx_hal_spi.o
obj-y += stm32f1xx_hal_sram.o
obj-y += stm32f1xx_hal_tim_ex.o
obj-y += stm32f1xx_hal_tim.o
obj-y += stm32f1xx_hal_uart.o
obj-y += stm32f1xx_hal_usart.o
obj-y += stm32f1xx_hal_wwdg.o
obj-y += stm32f1xx_hal.o



include $(RULE_DIR)/rules.mk
