
# CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Include
# CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Device/ST/STM32F1xx/Include
# CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver/Inc
# CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver

# CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/drivers/uart
CINCLUDE_FILE += catOS/include

# CINCLUDE_FILE += projects/demo/user/bsp/board_led


# subdir-y += bsp

obj-y += main.o

include $(RULE_DIR)/rules.mk
