
CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Include
CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Device/ST/STM32F1xx/Include
CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver/Inc
CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver

subdir-y += board_led
# subdir-y += iic
# subdir-y += lcd
# subdir-y += key

include $(RULE_DIR)/rules.mk
