

CINCLUDE_FILE += catOS/include

CINCLUDE_FILE += catOS/src/components/cat_error
CINCLUDE_FILE += catOS/src/components/cat_stdio

CINCLUDE_FILE += catOS/src/support


obj-y += mem_rw.o

include $(RULE_DIR)/rules.mk
