
#INCLUDE DIR FOR "stm32f103vet6_fire"
CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Include
CINCLUDE_FILE += catOS/bsp/Libraries/CMSIS/Device/ST/STM32F1xx/Include
CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver/Inc
CINCLUDE_FILE += catOS/bsp/Libraries/STM32F1xx_HAL_Driver

CINCLUDE_FILE += catOS/bsp/interface
CINCLUDE_FILE += catOS/bsp/interface/drivers

CINCLUDE_FILE += catOS/include
CINCLUDE_FILE += catOS/src/core/interrupt
CINCLUDE_FILE += catOS/src/core/schedule

#subdir
subdir-y += drivers
subdir-y += port

include $(RULE_DIR)/rules.mk
