
CINCLUDE_FILE += catOS/bsp/$(CATOS_BOARD_BSP)/drivers/uart

CINCLUDE_FILE += catOS/bsp/interface
CINCLUDE_FILE += catOS/include
CINCLUDE_FILE += catOS/src/core/interrupt
CINCLUDE_FILE += catOS/src/core/schedule

CINCLUDE_FILE += user

#subdir
subdir-y += drivers
subdir-y += port

include $(RULE_DIR)/rules.mk
